import { MenuItem, Category, DeliveryArea, Order } from "./types";

export const INITIAL_CATEGORIES: Category[] = [
  { id: "malfouf", name: "Malfouf", arabicName: "ملفوف MALFOUF", icon: "🌯", image: "https://images.unsplash.com/photo-1626700051175-6518c4793f4f?auto=format&fit=crop&q=80&w=800&h=600" },
  { id: "plats", name: "Les Plats", arabicName: "أطباق LES PLATS", icon: "🍽️", image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600" },
  { id: "pizza", name: "Pizza", arabicName: "بيتزا PIZZA", icon: "🍕", image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600" },
  { id: "pizza_mega", name: "Pizza Mega", arabicName: "بيتزا ميغا PIZZA MEGA", icon: "🍕", image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=600" },
  { id: "tacos", name: "Tacos", arabicName: "طاكوس TACOS", icon: "🌮", image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=800&h=600" },
  { id: "sandwich", name: "Sandwich", arabicName: "سندويش SANDWICH", icon: "🥪", image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=600" },
  { id: "burger", name: "Burger", arabicName: "برغر BURGER", icon: "🍔", image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600" },
  { id: "drinks", name: "Drinks", arabicName: "مشروبات DRINKS", icon: "🍹", image: "https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&q=80&w=800&h=600" },
  { id: "natural_juices", name: "Natural Juices", arabicName: "العصائر الطبيعية", icon: "🥤", image: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&q=80&w=600" },
  { id: "crepes", name: "Crepes", arabicName: "قسم الكراب", icon: "🥞", image: "https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&q=80&w=800&h=600" },
  { id: "sweet", name: "Sweet", arabicName: "حلويات SWEET", icon: "🍰", image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800&h=600" },
];

export const INITIAL_DELIVERY_AREAS: DeliveryArea[] = [
  { id: "area1", name: "الجزائر الوسطى (حيدرة / الأبيار / المرادية)", fee: 200, isActive: true, neighborhoods: "حي اللوتس، شارع ديدوش مراد، حي بومعطي" },
  { id: "area2", name: "شمال الجزائر (باب الوادي / بولوغين)", fee: 250, isActive: true, neighborhoods: "حي الساعات الثلاث، شارع بوعلام، حي بولوغين" },
  { id: "area3", name: "شرق الجزائر (باب الزوار / الدار البيضاء)", fee: 300, isActive: true, neighborhoods: "حي 5 جويلية، حي عدل، مقابل المطار الدولي" },
  { id: "area4", name: "غرب الجزائر (دالي ابراهيم / الشراقة)", fee: 300, isActive: true, neighborhoods: "عين الله، حي الكثبان، وسط الشراقة" },
  { id: "area5", name: "بئر مراد رايس وعين النعجة", fee: 350, isActive: true, neighborhoods: "حي عين النعجة، المجمع السكني الكبير" },
];

export const INITIAL_MENU: MenuItem[] = [
  // --- MALFOUF ---
  {
    id: "m1",
    name: "Malfouf Chicken Marinated",
    arabicName: "ملفوف دجاج ماريني",
    description: "Toasted soft wrap with specially marinated grilled chicken, sauce, and fries.",
    arabicDescription: "ملفوف بخبز الطاجين الساخن المحشو بالدجاج المتبل والمشوي، مع صلصة الثومية المقرمشة والبطاطا.",
    price: 300,
    category: "malfouf",
    image: "https://images.unsplash.com/photo-1626700051175-6518c4793f4f?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 142,
    isAvailable: true,
    reviews: []
  },
  {
    id: "m2",
    name: "Malfouf Viandache",
    arabicName: "ملفوف فيونداشي",
    description: "Premium minced beef wrap roasted inside a fresh traditional flatbread.",
    arabicDescription: "ملفوف بخبز التورتيلا واللحم المفروم المتبل الفاخر مع تشكيلة من الأجبان والصلصات اللذيذة.",
    price: 350,
    category: "malfouf",
    image: "https://images.unsplash.com/photo-1561651823-34fed022540e?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 98,
    isAvailable: true,
    reviews: []
  },
  {
    id: "m3",
    name: "Malfouf Liver",
    arabicName: "ملفوف كبدة",
    description: "Specially spiced grilled fresh liver wrap served with house sauces and fries.",
    arabicDescription: "ملفوف الكبدة المتبلة والمطهوة بامتياز مع رشة بصل وبقدونس وصلصة المطعم السرية الكلاسيكية.",
    price: 400,
    category: "malfouf",
    image: "https://images.unsplash.com/photo-1613514785940-daed07799d85?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 88,
    isAvailable: true,
    reviews: []
  },
  {
    id: "m4",
    name: "Malfouf Mix",
    arabicName: "ملفوف ميكس",
    description: "Combination of seasoned chicken, minced beef, and premium liver wrapped warmly.",
    arabicDescription: "المزيج الأسطوري الذي يجمع بين الدجاج الماريني الساخن، اللحم المفروم، والكبدة الغنية بالأجبان والبطاطا المقرمشة.",
    price: 450,
    category: "malfouf",
    image: "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 210,
    isAvailable: true,
    reviews: []
  },
  {
    id: "m5",
    name: "Calzone",
    arabicName: "كالزوني",
    description: "Stuffed and folded Italian oven-baked turnover pastry.",
    arabicDescription: "كالزوني المخبوز بفرننا الخاص بحشوة الدجاج، الموزاريلا الممتدة، والصلصة الإيطالية الفاخرة.",
    price: 500,
    category: "malfouf",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=500",
    rating: 4.6,
    salesCount: 75,
    isAvailable: true,
    reviews: []
  },
  {
    id: "m6",
    name: "Baguette Farcie Marinated Chicken",
    arabicName: "باغيت فورسي دجاج ماريني",
    description: "Fresh French traditional baguette stuffed with marinated chicken.",
    arabicDescription: "باغيت فرنسي طازج ومحمص، محشو بالدجاج الماريني المتبل الغني بالثومية والصلصة وصقيع الجبن.",
    price: 500,
    category: "malfouf",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 130,
    isAvailable: true,
    reviews: []
  },
  {
    id: "m7",
    name: "Baguette Farcie Viandache",
    arabicName: "باغيت فورسي فيونداشي",
    description: "Baked baguette filled with spiced minced beef and cheese layers.",
    arabicDescription: "خبز الباغيت المحشو باللحم المفروم الطازج المطبوخ بصلصاتنا الاستثنائية والأجبان الذائبة الوفيرة.",
    price: 500,
    category: "malfouf",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 112,
    isAvailable: true,
    reviews: []
  },
  {
    id: "m8",
    name: "Baguette Farcie Liver",
    arabicName: "باغيت فورسي كبدة",
    description: "Traditional baguette stuffed with premium grilled liver.",
    arabicDescription: "باغيت شهي مليء بالكبدة المفرومة الطازجة والمشوية بلمستنا الحارة والأجبان الفرنسية الفاخرة.",
    price: 500,
    category: "malfouf",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 95,
    isAvailable: true,
    reviews: []
  },
  {
    id: "m9",
    name: "Baguette Farcie Mix",
    arabicName: "باغيت فورسي ميكس",
    description: "Ultimate loaded baguette featuring a meat mix of chicken, minced beef, and liver.",
    arabicDescription: "الباغيت الأكبر والأقوى، المحشو بخليط من اللحم المفروم والكبدة والدجاج بصلصات حارة وجبنة جودا وموزاريلا.",
    price: 600,
    category: "malfouf",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 180,
    isAvailable: true,
    reviews: []
  },

  // --- LES PLATS ---
  {
    id: "p1",
    name: "Salad Plate",
    arabicName: "طبق سلاطة",
    description: "Fresh garden vegetable salad plate.",
    arabicDescription: "صحن مشكل من الخضار الطازجة المقرمشة والزيتون بزيت الزيتون والليمون.",
    price: 200,
    category: "plats",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=500",
    rating: 4.5,
    salesCount: 54,
    isAvailable: true,
    reviews: []
  },
  {
    id: "p2",
    name: "Tuna Salad Plate",
    arabicName: "طبق سلاطة طن",
    description: "Fresh garden vegetable salad plate topped with premium tuna slices.",
    arabicDescription: "مزيج الخضار المنعشة والبيض الطازج المغطى بكميات وافرة من التونة الرفيعة والصلصة الإيطالية.",
    price: 300,
    category: "plats",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=500",
    rating: 4.6,
    salesCount: 68,
    isAvailable: true,
    reviews: []
  },
  {
    id: "p3",
    name: "Shawarma Gratin Plate",
    arabicName: "طبق شاورما GRATIN",
    description: "Oven-baked gratin plate of sliced chicken shawarma over fries and hot cheese.",
    arabicDescription: "طبق الشاورما الأبرز بالفرن، مغطى بجبنة الموتزاريلا الفرنسية والقرواص والبيشاميل الشهية.",
    price: 500,
    category: "plats",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 240,
    isAvailable: true,
    reviews: []
  },
  {
    id: "p4",
    name: "Viandache Gratin Plate",
    arabicName: "طبق فيونداشي GRATIN",
    description: "Baked minced beef gratin with creamy cheese and golden fries.",
    arabicDescription: "طبق ساخن من اللحم المفروم المطهو مع الكريمة الطازجة والبطاطا المغطاة بطبقة غنية جداً من الأجبان الذائبة بالفرن.",
    price: 500,
    category: "plats",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 165,
    isAvailable: true,
    reviews: []
  },
  {
    id: "p5",
    name: "Shawarma Marinated Plate",
    arabicName: "طبق شاورما ماريني",
    description: "Generous serving of marinated chicken shawarma with fries, flatbread, and dips.",
    arabicDescription: "صحن فاخر يحتوي شاورما دجاج ماريني أصيل مع بطاطا فريت جولد، مقبلات الثومية وحمص متبل.",
    price: 600,
    category: "plats",
    image: "https://images.unsplash.com/photo-161651823-34fed022540e?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 195,
    isAvailable: true,
    reviews: []
  },
  {
    id: "p6",
    name: "Liver Plate",
    arabicName: "طبق كبدة",
    description: "Sautéed chicken or beef liver plate seasoned to perfection.",
    arabicDescription: "صحن تدليل عشاق الكبدة المشوية والمطهوة مع خضار، بصل محمّص وتوابل شرقية خاصة.",
    price: 600,
    category: "plats",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 110,
    isAvailable: true,
    reviews: []
  },
  {
    id: "p7",
    name: "Chicken Crispy Plate",
    arabicName: "طبق تشيكن كرسبي",
    description: "Deep-fried crispy chicken strips served with house dressing and fries.",
    arabicDescription: "صدور دجاج كرسبي فائقة القرمشة بخلطتنا الذهبية الخاصة، تُقدم مع البطاطا وصلصة الباربكيو الرائعة.",
    price: 700,
    category: "plats",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 185,
    isAvailable: true,
    reviews: []
  },
  {
    id: "p8",
    name: "Chicken Fries Plate",
    arabicName: "طبق تشيكن فرايز",
    description: "Fries topped with shredded chicken, warm melted cheddar cheese, and signature sauce.",
    arabicDescription: "الطبق الإدماني الشهير: جبل من البطاطا مغطى بقطع الدجاج المقرمش، شلال من جبنة الشيدر وصلصة الجبنة.",
    price: 700,
    category: "plats",
    image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 220,
    isAvailable: true,
    reviews: []
  },
  {
    id: "p9",
    name: "Escalope A La Creme",
    arabicName: "ESCALOPE A LA CREM",
    description: "Tender chicken breast escalope swimming in a rich mushroom cream sauce.",
    arabicDescription: "شريحة إسكالوب الدجاج الطرية والمطهوة على نار هادئة بصلصة كريمة الفطر الطازجة الغنية واللذيذة، يقدم مع أرز أو مقبلات.",
    price: 800,
    category: "plats",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 154,
    isAvailable: true,
    reviews: []
  },
  {
    id: "p10",
    name: "Chicken Cordon Bleu",
    arabicName: "CHICKEN CORDON BLEU",
    description: "Premium breaded chicken wrapped around ham and melted cheese.",
    arabicDescription: "صدر دجاج رول فاخر، محشو بالديك الرومي المدخن وجبنة الموزاريلا الذائبة، مقلي إلى سمرة ذهبية مقرمشة.",
    price: 1000,
    category: "plats",
    image: "https://images.unsplash.com/photo-1621510456681-23a23cfb5f57?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 142,
    isAvailable: true,
    reviews: []
  },

  // --- PIZZA ---
  {
    id: "pz1",
    name: "Pizza Classique",
    arabicName: "بيتزا عادي",
    description: "Classic Italian margherita pizza with tomato sauce and mozzarella.",
    arabicDescription: "بيتزا كلاسيكية بصلصة طماطم فلافيستا السرية وجبنة موزاريلا غنية.",
    price: 250,
    category: "pizza",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=500",
    rating: 4.6,
    salesCount: 310,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pz2",
    name: "Pizza Tuna",
    arabicName: "بيتزا طن",
    description: "Premium pizza topped with high-quality tuna, olives, and cheese.",
    arabicDescription: "بيتزا غنية بقطع التونة الرفيعة والزيتون الأسود وموزاريلا بلدية.",
    price: 350,
    category: "pizza",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 204,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pz3",
    name: "Pizza Viandache",
    arabicName: "بيتزا فيونداشي",
    description: "Minced beef, sweet peppers, and loaded cheese over pizza crust.",
    arabicDescription: "بيتزا اللحم المفروم الطازج المتبل بلمستنا الخاصة مع البصل والفلفل والأجبان الذائبة.",
    price: 350,
    category: "pizza",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 250,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pz4",
    name: "Pizza Shawarma",
    arabicName: "بيتزا شاورما",
    description: "Delicious freshly shaved chicken shawarma slices baked onto pizza pastry.",
    arabicDescription: "الاندماج الخرافي بين عجينة البيتزا وحشوة شاورما الدجاج المحبوبة مع الكريمة والجبن.",
    price: 350,
    category: "pizza",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 290,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pz5",
    name: "Pizza Vegetarian",
    arabicName: "بيتزا فيجتريان",
    description: "Brimming with fresh mushrooms, corn, bell peppers, tomatoes, and olives.",
    arabicDescription: "بيتزا الخضار المشكلة الطازجة: فلفل حلو، بصل، فطر، ذرة حلوة، زيتون وموزاريلا.",
    price: 350,
    category: "pizza",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=500",
    rating: 4.5,
    salesCount: 95,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pz6",
    name: "Pizza Merguez",
    arabicName: "بيتزا مرقاز",
    description: "Topped with fresh traditional Algerian merguez sausages and cheese.",
    arabicDescription: "بيتزا المرقاز البلدي الطازج والمحمص الغني بالتوابل والصلصة والريحان المدهش.",
    price: 400,
    category: "pizza",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 185,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pz7",
    name: "Pizza Royal",
    arabicName: "بيتزا رويال",
    description: "Royal treat baked with a variety of chicken, meat, mushrooms, and cheese.",
    arabicDescription: "البيتزا الملوكية: شاورما دجاج، لحم مفروم، فطر طازج، مخللات وزيتون مع شلال الموزاريلا.",
    price: 500,
    category: "pizza",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 330,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pz8",
    name: "Pizza Couvre",
    arabicName: "بيتزا كوفار",
    description: "Calzone-style covered layered pizza with robust cheese stuffing.",
    arabicDescription: "بيتزا كوفار المغطاة بطبقتين من العجين الذهبي، محشوة باللحم المفروم والدجاج والصلصلة وصلصة الجبن الغنية.",
    price: 500,
    category: "pizza",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 154,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pz9",
    name: "Pizza 4 Fromages",
    arabicName: "بيتزا 4 فرماج",
    description: "Four cheeses blend: Mozzarella, cheddar, blue cheese, and gouda.",
    arabicDescription: "بيتزا الأجبان الأربعة الفاخرة لعشاق الامتداد والمذاق القوي: موزاريلا، شيدر، ريكوتا، وجبن أزرق.",
    price: 600,
    category: "pizza",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 220,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pz10",
    name: "Pizza 4 Saisons",
    arabicName: "بيتزا 4 سيزون",
    description: "Divided in quarters featuring tuna, chicken, vegy, and meat toppings.",
    arabicDescription: "بيتزا الفصول الأربعة المقسمة لترضي كل الأذواق: جزء تونة، جزء لحم مفروم، جزء شاورما، وجزء خضار وفطر.",
    price: 600,
    category: "pizza",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 175,
    isAvailable: true,
    reviews: []
  },

  // --- PIZZA MEGA ---
  {
    id: "pm1",
    name: "Pizza XL",
    arabicName: "بيتزا XL",
    description: "Huge extra-large single-topping pizza.",
    arabicDescription: "بيتزا بحجم عائلي كبير XL بصلصة طماطم وموزاريلا رائعة تناسب الجمعات واللقاءات.",
    price: 800,
    category: "pizza_mega",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 120,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pm2",
    name: "Pizza Royal XL",
    arabicName: "بيتزا رويال XL",
    description: "Extra large pizza loaded with various delicious meats and extras.",
    arabicDescription: "الحجم العائلي الفخم المحشو بقطع اللحم المفروم، الدجاج المطهو، الزيتون وصلصة الكبّار الشهية والموزاريلا الوفيرة.",
    price: 900,
    category: "pizza_mega",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 145,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pm3",
    name: "Pizza 4 Saisons XL",
    arabicName: "بيتزا 4 سيزون XL",
    description: "Gigantic quarters of diverse delicious pizza flavors.",
    arabicDescription: "بيتزا الفصول الأربعة بحجم عائلي ضخم XL تلبي رغبة الجميع في الوجبة والمشاركة.",
    price: 1000,
    category: "pizza_mega",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 130,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pm4",
    name: "Pizza Chef XL",
    arabicName: "بيتزا شاف XL",
    description: "The chef's oversized masterpiece pizza.",
    arabicDescription: "بيتزا الشيف المليئة بالثوم المكرمل، شرائح السلامي، المشروم الفريش وأجبان إيمانتال وموزاريلا XL.",
    price: 1200,
    category: "pizza_mega",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 110,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pm5",
    name: "Pizza Mega Royal",
    arabicName: "بيتزا ميغا رويال",
    description: "Massive super size royal family pizza.",
    arabicDescription: "مستوى آخر من اللذة والعملقة: بيتزا ميغا الرويـال الكبيرة جداً المغطاة بكثافة باللحوم والدجاج والزيتون والأجبان الممتدة.",
    price: 1500,
    category: "pizza_mega",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 95,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pm6",
    name: "Pizza Mega 4 Saisons",
    arabicName: "بيتزا ميغا 4 سيزون",
    description: "Enormous four seasons sharing pizza.",
    arabicDescription: "الميغا الكبيرة للغاية بالتقسيم الرباعي الشامل لكل المذاقات المفضلة لديكم بأفضل جودة طعام.",
    price: 1800,
    category: "pizza_mega",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 78,
    isAvailable: true,
    reviews: []
  },
  {
    id: "pm7",
    name: "Pizza Mega Chef",
    arabicName: "بيتزا ميغا شاف",
    description: "Insanely huge ultimate chef pizza creation.",
    arabicDescription: "البيتزا الأكبر حجماً على الإطلاق في قائمة فلافيستا: تحفة الشيف بخلطة سرية ولحوم مدخنة وقشرة محشوة بالجبن.",
    price: 2500,
    category: "pizza_mega",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 64,
    isAvailable: true,
    reviews: []
  },

  // --- TACOS ---
  {
    id: "tc1",
    name: "Tacos Shawarma",
    arabicName: "طاكوس شاورما",
    description: "Toasted flour tortilla loaded with seasoned chicken shawarma and cheese sauce.",
    arabicDescription: "طاكوس فرنسي غني بشاورما الدجاج اللذيذة وصلصة الجبن والبطاطس المقرمشة.",
    price: 350,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 310,
    isAvailable: true,
    reviews: []
  },
  {
    id: "tc2",
    name: "Tacos Viandache",
    arabicName: "طاكوس فيونداشي",
    description: "Stuffed with seasoned fresh minced beef and warm cheese.",
    arabicDescription: "طاكوس اللحم المفروم المتبل الفاخر الغني بصلصة الألجيريان اللذيذة والأجبان الفاخرة.",
    price: 400,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 220,
    isAvailable: true,
    reviews: []
  },
  {
    id: "tc3",
    name: "Tacos Liver",
    arabicName: "طاكوس كبدة",
    description: "Spiced chopped liver tacos toasted in traditional wraps.",
    arabicDescription: "طاكوس الكبدة المتبلة والمجمرة مع رشة بصل وبقدونس وصلصة ألجيريان الغنية والأجبان المفضلة.",
    price: 450,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 110,
    isAvailable: true,
    reviews: []
  },
  {
    id: "tc4",
    name: "Tacos Merguez",
    arabicName: "طاكوس مرقاز",
    description: "Sautéed aromatic merguez tacos.",
    arabicDescription: "المرقاز البلدي الجزائري المحمر بداخل طاكوس ساخن مع بطاطس فريت وصلصة الجبنة المنزلية الوفيرة.",
    price: 400,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 180,
    isAvailable: true,
    reviews: []
  },
  {
    id: "tc5",
    name: "Tacos Gratine",
    arabicName: "طاكوس غراتيني",
    description: "Toasted tacos topped with melted mozzarella and white sauce in oven.",
    arabicDescription: "طاكوس غراتيني مغطى بصلصة الكريمة والموزاريلا ويدخل الفرن ليصبح ذهبياً ممتداً ومقرمشاً.",
    price: 450,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 215,
    isAvailable: true,
    reviews: []
  },
  {
    id: "tc6",
    name: "Tacos Panache",
    arabicName: "طاكوس بناشي",
    description: "Luxurious meat mix tacos with double cheese.",
    arabicDescription: "طاكوس رائع يجمع بين ثنائية شاورما الدجاج واللحم المفروم بصلصة الجبن والباربكيو الغنية.",
    price: 500,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 290,
    isAvailable: true,
    reviews: []
  },
  {
    id: "tc7",
    name: "Tacos Chicken Crispy",
    arabicName: "طاكوس تشيكن كرسبي",
    description: "Wrapped fried crunchy chicken tenders.",
    arabicDescription: "طاكوس الدجاج المقرمش الكرسبي الطري والغني بصلصة الساموراي الحارة وصلصة الجبنة الكثيفة.",
    price: 500,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 234,
    isAvailable: true,
    reviews: []
  },
  {
    id: "tc8",
    name: "Tacos XL",
    arabicName: "طاكوس XL",
    description: "Larger size tacos with triple chicken/meat portions.",
    arabicDescription: "الحجم الكبير المعزز من الطاكوس ليتسع للمزيد من الدجاج واللحم والجبن والبطاطس لمتعة مضاعفة.",
    price: 600,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 165,
    isAvailable: true,
    reviews: []
  },
  {
    id: "tc9",
    name: "Tacos XXL",
    arabicName: "طاكوس XXL",
    description: "Gigantic double sized tacos.",
    arabicDescription: "طاكوس عملاق XXL لعشاق الشبع والمشاركة بخلطة اللحوم الثلاثية والموزاريلا الوفيرة.",
    price: 900,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 110,
    isAvailable: true,
    reviews: []
  },
  {
    id: "tc10",
    name: "Tacos XXXL",
    arabicName: "طاكوس XXXL",
    description: "Insanely huge ultimate tacos experience.",
    arabicDescription: "الطاكوس المدمر الخارق المعبأ باللحوم والدجاج والكرسبي وصلصة الجرجير والأجبان المتتالية.",
    price: 1200,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 85,
    isAvailable: true,
    reviews: []
  },
  {
    id: "tc11",
    name: "Tacos Giga",
    arabicName: "طاكوس جيغا",
    description: "The ultimate heaviest Giga Tacos model.",
    arabicDescription: "أكبر حركات طاكوس على الإطلاق بمطعم فلافيستا: جبل من الشاورما والفيونداشي والكرسبي والبطاطا الكافية لـ 4 أشخاص بامتياز.",
    price: 2500,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 43,
    isAvailable: true,
    reviews: []
  },

  // --- SANDWICH ---
  {
    id: "sd1",
    name: "Sandwich Viandache",
    arabicName: "سندويش فيونداشي",
    description: "Minced beef baguette with dynamic seasoned dressings.",
    arabicDescription: "سندويش اللحم المفروم الشهي المحمر بالطماطم، الخس، البصل وصلصة الساموراي بلذة تفوق الوصف.",
    price: 200,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.6,
    salesCount: 198,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd2",
    name: "Sandwich Shawarma",
    arabicName: "سندويش شاورما",
    description: "Tasty bread sandwich filled with marinated chicken shawarma.",
    arabicDescription: "سندويش الخبز الطازج المعبأ بقطع الشاورما الساخنة وكريمة الثوم المذهلة والمخللات.",
    price: 250,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 260,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd3",
    name: "Sandwich Merguez",
    arabicName: "سندويش مرقاز",
    description: "Perfectly spiced merguez baguette.",
    arabicDescription: "سندويش المرقاز الجزائري المشوي والمحمر مع بطاطس وسلطة وشرائح البصل والصلصات الساخنة.",
    price: 300,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 140,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd4",
    name: "Sandwich Liver",
    arabicName: "سندويش كبدة",
    description: "Freshly sautéed liver chunks in warm baguette.",
    arabicDescription: "الخبز الطازج المحشو بالكبدة المقرمشة المشوية مع توابل وبهارات المطعم الرائعة وصلصة المايونيز.",
    price: 300,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 125,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd5",
    name: "Sandwich Shawarma Spicy",
    arabicName: "سندويش شاورما سبايسي (SPICY)",
    description: "Hot spicy chicken shawarma sub.",
    arabicDescription: "لمحبي الحماس والحرارة الشديدة: شاورما دجاج متبلة بصلصة الهريسة الحارة وشرائح الفلفل الحار والصلصة الحريفة.",
    price: 350,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 210,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd6",
    name: "Sandwich Kebab",
    arabicName: "سندويش كباب",
    description: "Grilled juicy kebab skewers wrapped warmth with dressings.",
    arabicDescription: "كباب لحم بقري مدخن على الجمر بالطريقة التقليدية مع صلصة الترتار، بصل وبقدونس بخبزنا الممتاز.",
    price: 400,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 165,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd7",
    name: "Eish Shawarma",
    arabicName: "عيش شاورما عادي",
    description: "Fresh seasoned shawarma served inside soft pita bread.",
    arabicDescription: "ساندويش شاورما دجاج بخبز العيش اللبناني الساخن والخفيف مع الثومية والبطاطس والمخلل.",
    price: 300,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 120,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd8",
    name: "Eish Shawarma Mix",
    arabicName: "عيش شاورما ميكس MIX",
    description: "Double filled mix of chicken and meats in pita bread.",
    arabicDescription: "عيش لبناني طازج مع مزيج من شاورما الدجاج واللحم المفروم والأجبان في عيش لذيذ ومشبع.",
    price: 450,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 154,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd9",
    name: "Shamy Shawarma",
    arabicName: "شامي شاورما عادي",
    description: "Traditional Shamy shawarma pocket wrap.",
    arabicDescription: "شاورما دجاج بخبز الشامي الرائع ذو المذاق الرائع والموزون بالأجبان.",
    price: 300,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 95,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd10",
    name: "Shamy Shawarma Mix",
    arabicName: "شامي شاورما ميكس MIX",
    description: "Tasty full-loaded Shamy shawarma mix wrap.",
    arabicDescription: "خلطة الشاورما والفيونداشي والجبن بداخل الخبز الشامي الرائع والشهي المحمص.",
    price: 450,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 130,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd11",
    name: "Panini Shawarma",
    arabicName: "بانيني شاورما عادي",
    description: "Hot pressed Italian style panini bread stuffed chicken shawarma.",
    arabicDescription: "خبز البانيني الشهير المحمص بالماكينة، محشو بشاورما الدجاج اللذيذة والجبنة الممتدة.",
    price: 300,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 142,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd12",
    name: "Panini Shawarma Mix",
    arabicName: "بانيني شاورما ميكس MIX",
    description: "Loaded meats mix pressed inside hot panini crust.",
    arabicDescription: "دجاج متبل ولحم مفروم وجبنة شيدر غنية مضغوطة ومحمصة بامتياز بداخل بانيني ساخن.",
    price: 450,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 165,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd13",
    name: "Makloub Classique",
    arabicName: "مقلوب عادي",
    description: "Tunisian makloub dough wrap filled with chicken and cheese.",
    arabicDescription: "ساندويش المقلوب التونسي الشهير المخبوز بالعجين الطازج المحشو بالدجاج الماريني والهريسة والجبن.",
    price: 350,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 180,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd14",
    name: "Makloub Mix",
    arabicName: "مقلوب ميكس MIX",
    description: "Loaded combination inside baked makloub crust.",
    arabicDescription: "المقلوب الرويال الذهبي المعبأ بشاورما، لحم مفروم، فريت، وأسرار الصلصة والجبن.",
    price: 500,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 220,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd15",
    name: "Fajitas Classique",
    arabicName: "فاخيتاس عادي",
    description: "Stir fried seasoned peppers and chicken fajita wrap.",
    arabicDescription: "الفاجيتاس المكسيكية بالدجاج والتوابل الملونة والفلفل البارد والصلصة والجبن بخبز التورتيلا.",
    price: 450,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 135,
    isAvailable: true,
    reviews: []
  },
  {
    id: "sd16",
    name: "Fajitas Mix",
    arabicName: "فاخيتاس ميكس MIX",
    description: "Rich loaded chicken and beef fajitas wrap.",
    arabicDescription: "فاجيتاس مليئة بخليط الدجاج مع اللحم البقري الشرائح ببهارات ممتازة وأجبان فرنسية ساخنة.",
    price: 600,
    category: "sandwich",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 168,
    isAvailable: true,
    reviews: []
  },

  // --- BURGER ---
  {
    id: "bg1",
    name: "Burger Classique",
    arabicName: "برغر كلاسيك",
    description: "Classic grilled beef burger patty with cheddar slice and sauce.",
    arabicDescription: "برغر لحم بقري كلاسيكي مشوي مع شريحة شيدر ذائبة، طماطم، خس، وصلصة برغر الممتازة.",
    price: 350,
    category: "burger",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 350,
    isAvailable: true,
    reviews: []
  },
  {
    id: "bg2",
    name: "Crispy Chicken Burger",
    arabicName: "برغر تشيكن كرسبي",
    description: "Deep fried crunchy chicken chicken breast with lettuce and cream.",
    arabicDescription: "صدر دجاج كرسبي مقلي ومقرمش بطبقتنا الخاصة، خس، صلصة المايونيز والجبنة اللذيذة.",
    price: 350,
    category: "burger",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 290,
    isAvailable: true,
    reviews: []
  },
  {
    id: "bg3",
    name: "Double Burger",
    arabicName: "برغر DOUBLE",
    description: "Two grilled patties, double melted cheese, and double joy.",
    arabicDescription: "برغر العملاق: قطعتين لحم كاملة مشوية بامتياز، قطعتين شيدر ذائبة، خضار طازجة وصلصة فلافيستا الخاصة.",
    price: 500,
    category: "burger",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 420,
    isAvailable: true,
    reviews: []
  },
  // --- DRINKS ---
  {
    id: "dr1",
    name: "Soft Drinks",
    arabicName: "المشروبات الغازية",
    description: "Assorted cold soft drinks (Coca-Cola, Hamoud Boualem, Selecto, Fanta, Pepsi, Sprite).",
    arabicDescription: "تشكيلة مشروبات غازية باردة ومنعشة حسب اختيارك (كوكاكولا، حمود بوعلام، سيلكتو، فانتا، بيبسي، سبرايت).",
    price: 150,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 160,
    isAvailable: true,
    reviews: []
  },
  {
    id: "dr2",
    name: "Natural Fresh Juices",
    arabicName: "المشروبات الطبيعية (عصائر طازجة)",
    description: "Premium selection of freshly squeezed seasonal fruits natural juice.",
    arabicDescription: "عصائر طبيعية طازجة ومحضرة يومياً من الفواكه الموسمية اللذيذة والمنعشة الخالية من المواد الحافظة (عصير برتقال، ليمون بالنعناع، فراولة).",
    price: 300,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=crop&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 198,
    isAvailable: true,
    reviews: []
  },
  // --- ADDED SOFT DRINKS PROMPT ITEMS ---
  {
    id: "dr-slim-33",
    name: "Slim 33 ml",
    arabicName: "سليم 33 ml",
    description: "Cold Slim soft drink 33 ml size.",
    arabicDescription: "مشروب غازي سليم بارد ومنعش حجم 33 ml.",
    price: 100,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 45,
    isAvailable: true,
    reviews: []
  },
  {
    id: "dr-slim-1l",
    name: "Slim 1L",
    arabicName: "سليم 1L",
    description: "Cold Slim soft drink 1L size.",
    arabicDescription: "مشروب غازي سليم بارد ومنعش حجم عائلي 1 لتر.",
    price: 200,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 30,
    isAvailable: true,
    reviews: []
  },
  {
    id: "dr-selecto-33",
    name: "Selecto 33 ml",
    arabicName: "سيلكتو 33 ml",
    description: "Cold Selecto soft drink 33 ml size.",
    arabicDescription: "المشروب الجزائري العريق سيلكتو مبرد ولذيذ حجم 33 ml.",
    price: 100,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 85,
    isAvailable: true,
    reviews: []
  },
  {
    id: "dr-selecto-1l",
    name: "Selecto 1L",
    arabicName: "سيلكتو 1L",
    description: "Cold Selecto soft drink 1L size.",
    arabicDescription: "المشروب الجزائري العريق سيلكتو حجم عائلي 1 لتر.",
    price: 200,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 70,
    isAvailable: true,
    reviews: []
  },
  {
    id: "dr-farha-33",
    name: "Farha 33 ml",
    arabicName: "فرحة 33 ml",
    description: "Cold Farha soft drink 33 ml size.",
    arabicDescription: "مشروب فرحة الغازي اللذيذ والمبرد حجم 33 ml.",
    price: 100,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 40,
    isAvailable: true,
    reviews: []
  },
  {
    id: "dr-farha-1l",
    name: "Farha 1L",
    arabicName: "فرحة 1L",
    description: "Cold Farha soft drink 1L size.",
    arabicDescription: "مشروب فرحة الغازي اللذيذ حجم عائلي 1 لتر.",
    price: 200,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=500",
    rating: 4.7,
    salesCount: 35,
    isAvailable: true,
    reviews: []
  },
  {
    id: "dr-jofree-33",
    name: "Jofree Juice 33 ml",
    arabicName: "عصير جوفري 33 ml",
    description: "Jofree fruit juice 33 ml size.",
    arabicDescription: "عصير جوفري المنعش والبارد حجم 33 ml.",
    price: 120,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 50,
    isAvailable: true,
    reviews: []
  },
  {
    id: "dr-jofree-1l",
    name: "Jofree Juice 1L",
    arabicName: "عصير جوفري 1L",
    description: "Jofree fruit juice 1L size.",
    arabicDescription: "عصير جوفري المنعش واللذيذ حجم عائلي 1 لتر.",
    price: 250,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 45,
    isAvailable: true,
    reviews: []
  },
  {
    id: "dr-water-33",
    name: "Water Bottle 33 ml",
    arabicName: "قارورة ماء 33 ml",
    description: "Pure mineral water bottle 33 ml size.",
    arabicDescription: "قارورة مياه معدنية نقية وشديدة البرودة حجم 33 ml.",
    price: 50,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 160,
    isAvailable: true,
    reviews: []
  },
  {
    id: "dr-water-1l",
    name: "Water Bottle 1L",
    arabicName: "قارورة ماء 1L",
    description: "Pure mineral water bottle 1L size.",
    arabicDescription: "قارورة مياه معدنية طبيعية وصحية حجم 1 لتر.",
    price: 100,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 120,
    isAvailable: true,
    reviews: []
  },
  // --- ADDED NATURAL JUICES ---
  {
    id: "nj-fruit-juice",
    name: "Fruit Juice",
    arabicName: "عصير فواكه",
    description: "100% fresh squeezed natural fruit juice mix.",
    arabicDescription: "عصير فواكه طبيعي طازج ومحضر من تشكيلة شهية من الفواكه المنعشة يومياً.",
    price: 350,
    category: "natural_juices",
    image: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 75,
    isAvailable: true,
    reviews: []
  },
  // --- ADDED CRÊPES ---
  {
    id: "cr-choco",
    name: "Chocolate Crepe",
    arabicName: "كراب شيكولاتة",
    description: "Golden crepe filled with rich melted milk chocolate.",
    arabicDescription: "كراب ذهبي طازج بفرننا الخاص ومحشو بشوكولاتة مشكلة فاخرة ممتدة ولذيذة.",
    price: 300,
    category: "crepes",
    image: "https://images.unsplash.com/photo-1519676867240-f03562e6ae55?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 90,
    isAvailable: true,
    reviews: []
  },
  {
    id: "cr-banana",
    name: "Banana Crepe",
    arabicName: "كراب بنان",
    description: "Golden crepe with premium chocolate and sweet banana slices.",
    arabicDescription: "كراب طازج محشو بشوكولاتة نوتيلا الغنية مع قطع الموز (البنان) الطازجة والشهية.",
    price: 350,
    category: "crepes",
    image: "https://images.unsplash.com/photo-1547058881-aa0edd92aab3?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 110,
    isAvailable: true,
    reviews: []
  },
  {
    id: "cr-strawberry",
    name: "Strawberry Crepe",
    arabicName: "كراب فراولة",
    description: "Delicious crepe loaded with Nutella and fresh strawberry slices.",
    arabicDescription: "كراب طازج وساخن محشو بالشوكولاتة وقطع الفراولة البلدية الطازجة اللذيذة ورشة أبهى السكريات.",
    price: 380,
    category: "crepes",
    image: "https://images.unsplash.com/photo-1622484211148-7164bbd978a6?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 95,
    isAvailable: true,
    reviews: []
  },
  {
    id: "cr-mix",
    name: "Mix Crepe",
    arabicName: "كراب ميكس",
    description: "The ultimate crepe loaded with chocolate, banana, and strawberry slices.",
    arabicDescription: "تحفة الكراب الاستثنائية: شوكولاتة نوتيلا ممتدة مع خليط الموز والفراولة ورقائق اللوز المقرمشة والمكسرات.",
    price: 450,
    category: "crepes",
    image: "https://images.unsplash.com/photo-1612240498936-65f5101365d2?auto=format&fit=crop&q=80&w=500",
    rating: 4.9,
    salesCount: 150,
    isAvailable: true,
    reviews: []
  },
  // --- SWEETS ---
  {
    id: "sw1",
    name: "Crêpe Nutella Chocolate",
    arabicName: "كراب (Crêpe) شوكولاتة ونوتيلا",
    description: "Delicious sweet crepe folded and loaded with rich Nutella chocolate, fresh banana slices, and nuts.",
    arabicDescription: "كراب حلو ساخن ومميز محشو بكمية سخية من شوكولاتة نوتيلا الفاخرة، مع قطع الموز الطازجة والمكسرات المقرمشة اللذيذة.",
    price: 350,
    category: "sweet",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=500",
    rating: 4.8,
    salesCount: 220,
    isAvailable: true,
    reviews: []
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "order-101",
    orderNumber: "S-1201",
    items: [
      {
        menuItem: INITIAL_MENU[0],
        quantity: 2
      }
    ],
    customerName: "ياسين برلماني",
    customerPhone: "0550123456",
    deliveryType: "dine_in",
    tableNumber: "04",
    deliveryFee: 0,
    notes: "يرجى تحمير الملفوف جيداً وشكراً لكم",
    status: "new",
    total: 600,
    createdAt: "2026-06-11T08:14:00.000Z"
  }
];
